
# ---- memory configuration
# our dtlog uses at least 1k
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=32768


# ---- system, kernel, logging and console configuration
# see DTMC_ZEPHYR_SYSTEM_COMMON.conf included by CMakeLists.txt

# ---- bluetooth configuration
# see DTMC_ZEPHYR_RPC_HOST_COMMON.conf included by CMakeLists.txt

# ---- CoAP configuration
# see DTMC_ZEPHYR_OPENTHREAD_COAP_COMMON.conf included by CMakeLists.txt

# ---- CAN configuration
# see DTMC_ZEPHYR_DTIOX_CAN_COMMON.conf included by CMakeLists.txt
