
# ---- memory configuration
# our dtlog uses at least 1k
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=32768


# ---- system, kernel, logging and console configuration
# see DTMC_ZEPHYR_SYSTEM_COMMON.conf included by CMakeLists.txt

# ---- modbus configuration
# see DTMC_ZEPHYR_DTXIO_MODBUS_COMMON.conf included by CMakeLists.txt
