# =========================
# UART support
# =========================

# UART allow setting runtime configuration such as baud rate
CONFIG_UART_USE_RUNTIME_CONFIGURE=y             

# dtiox_zephyr_uart runs on the new interrupt API
CONFIG_UART_INTERRUPT_DRIVEN=y
