# =========================
# Modbus support
# =========================

CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_CLIENT_SERVER=y
CONFIG_MODBUS_SERIAL=y

# UART allow setting runtime configuration such as baud rate
CONFIG_UART_USE_RUNTIME_CONFIGURE=y             

# dtiox_zephyr_uart runs on the new interrupt API
CONFIG_UART_INTERRUPT_DRIVEN=y
