
# =========================
# CAN support (classic CAN)
# =========================

# Enable gpio
CONFIG_GPIO=y

# enables the support for getting the current configurations of GPIOs
CONFIG_GPIO_GET_CONFIG=y

# enables the support for getting the current direction of GPIOs
CONFIG_GPIO_GET_DIRECTION=y