# ---- Openthread CoAP configuration
CONFIG_OPENTHREAD=y
CONFIG_OPENTHREAD_COAP=y
CONFIG_OPENTHREAD_SRP_CLIENT=y
CONFIG_OPENTHREAD_LOG_LEVEL_DYNAMIC=y
CONFIG_OPENTHREAD_LOG_LEVEL_DEBG=y
CONFIG_OPENTHREAD_CUSTOM_PARAMETERS="-DOPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1 -DOPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_API_ENABLE=1 -DOPENTHREAD_CONFIG_SRP_CLIENT_AUTO_START_DEFAULT_MODE=1"
