CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y

# Optional but useful
CONFIG_SHELL_PROMPT_UART="dtmc_zephyr> "
CONFIG_SHELL_CMD_BUFF_SIZE=128
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_TAB=y

# Allow rebooting from shell command, which is useful for testing and debugging
CONFIG_REBOOT=y