CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=32768

# ---- newlib configuration
CONFIG_NEWLIB_LIBC=y
# without this, PRIu64 doesn't work in printf or printk
CONFIG_NEWLIB_LIBC_NANO=n
# enable float support in printf, adds 1-2kB to the binary
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# ---- console configuration
CONFIG_STDOUT_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# ---- logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# ---- kernel configuration
CONFIG_EVENTS=y
CONFIG_KERNEL_SHELL=y

# --- main thread priority as "pre-emptible normal" midrange between 0 (highest) and 15 (lowest aka idle)
CONFIG_MAIN_THREAD_PRIORITY=7

# ---- system clock configuration
# makes Zephyr tick every 1 ms instead of the default 100 Hz (10 ms)
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# ---- thread monitoring and analysis
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER_AUTO=n

# ==== stack overflow detection and diagnostics
CONFIG_STACK_SENTINEL=y
CONFIG_STACK_CANARIES=y

# ==== random number generation
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=n   # make sure you don't get the fake test RNG
